
// 财务中心
export const apiFinance = {
    "assets" : '/api/Finance/assets',
    "weituo" : '/api/Finance/weituo',
    "chexiao" : '/api/Finance/chexiao',

    "userQianbaoList" : '/api/Finance/userQianbaoList',
    "myyhks" : '/api/Finance/myyhks',
    "area" : '/api/Finance/area',
    "bankList" : '/api/Finance/bankList',
    "upbank" : '/api/Finance/upbank',
    "delbank" : '/api/Finance/delbank',
    "defaultbank" : '/api/Finance/defaultbank',
    "chengjiao" : '/api/Finance/chengjiao',

    "pay" : '/api/Finance/aliAndWechat',
    "updatepay" : '/api/Finance/updateUseraccount',
    "deletepay" : '/api/Finance/delaccount',


    "coinList" : '/api/Finance/coinList',
    "listWallet" : '/api/Finance/myQianbao',
    "upqianbao" : '/api/Finance/upqianbao',
    "delWallet" : '/api/Finance/delQianbao',

    "myzcLog" : '/api/Finance/myzcLog',
    "myzrLog" : '/api/Finance/myzrLog',
    "takeCoinVerify" : '/api/Finance/verify',
    "myasset" : '/api/Finance/myasset',
    "upmyzc" : '/api/Finance/upmyzc',
    "upmyzr" : '/api/Finance/upmyzr',
    "myzrads" : '/api/Finance/myzrads',
    "zcother" : '/api/Finance/zcother',
    "ZcListOfIn" : '/api/Finance/ZcListOfIn',
    "freal" : '/api/Finance/freal',
    "transLog" : '/api/Finance/transLog',
    // "myaddrstatus" : '/api/Finance/myaddrstatus',
    "activateAddr" : '/api/Finance/activateAddr',
    "invitList" : '/api/Finance/invitList',
    "invit" : '/api/Finance/invit',
    "spreadActive" : '/api/Finance/spreadActive',

    // "delKey" : '/api/Finance/delKey',

    "loginlog" : '/api/Security/loginlog',
    "basicinfo" : '/api/Security/basicinfo',
    "question" : '/api/Security/question',
    "upquestion" : '/api/Security/upquestion',
    "uppaypassword" : '/api/Security/uppaypassword',
    "findPayPwdVerify" : '/api/Security/findPayPwdVerify',
    "findPayPwd" : '/api/Security/findPayPwd',
    "uppassword" : '/api/Security/uppassword',
    "dcType" : '/api/Security/dcType',
    "nameauth" : '/api/Security/nameauth',
    "ga" : '/api/Security/ga',
    "bindGa" : '/api/Security/bindGa',
    "unbindGa" : '/api/Security/unbindGa',
    "setGaVerify" : '/api/Security/setGaVerify',
    "upmobleVerify" : '/api/security/upmobleVerify',
    "upmoble" : '/api/Security/upmoble',
    "payPasswordVerifyCode":"/api/Security/payPasswordVerifyCode",
    "withdrawVerifyCode":"/api/Finance/withdrawVerifyCode",
    "getMainCoins":"/api/finance/getMainCoins",
};

